# Generated by Django 4.2.11 on 2025-12-19 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной'), django.core.validators.MaxValueValidator(1000000, message='Цена не может превышать 1,000,000 руб.')], verbose_name='Цена билета')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Вместимость должна быть хотя бы 1')], verbose_name='Вместимость')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Есть проектор')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время сеанса')),
                ('seats_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Не может быть отрицательное количество мест')], verbose_name='Свободных мест')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='museum.exhibition')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='museum.hall')),
            ],
        ),
    ]
